In [ ]:
import pandas as pd

In [ ]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['Sia','Ravi','Geet','Ajeenkya','Avinash'])
marks = pd.Series([85,67,59,40,90])

In [ ]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks': marks
})

In [ ]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [ ]:
df.shape

(5, 3)

In [ ]:
df.size

15

In [ ]:
df.ndim

2

In [ ]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [ ]:
pwd

'/content'

In [ ]:
df = pd.read_csv("student.csv")

In [ ]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [ ]:
df2 = pd.read_csv("student3.tsv")

In [ ]:
df2

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21